### ISSUE TITLE
Failed to import required modules in sdk

### ISSUE THREAD

**Issue by enginebai** [enginebai/PyMedium#12]
```python
>>> from PyMedium.medium import Medium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enginebai/tmp/med/env/lib/python3.5/site-packages/PyMedium/medium.py", line 5, in <module>
    import requests
ImportError: No module named 'requests'
```

**Comment by enginebai** [comment]
Fixed in `v1.0.3`
